
export default {
  SAVE_ARRAY: "SAVE_ARRAY",
  CLEAN_ARRAY: "CLEAN_ARRAY",
  SUM_PRICE: "SUM_PRICE",
  SUBS_PRICE: "SUBS_PRICE",
  CHECK_ORDERS: "CHECK_ORDERS",
  CLEAN_ORDERS: "CLEAN_ORDERS",
  SAVE_BARNAME: "SAVE_BARNAME"
}
